### ISSUE TITLE
Goal: get the TI-84 banned in all schools

### ISSUE THREAD

**Issue by alessiodam** [chromalock/TI-32#7]
Nice goal lmfao, nice project though!

**Comment by BrainwashAlpha** [comment]
If all the neurodivergent middle and high schoolers find this project from youtube recommendations and build it, I think we'll easily achieve this goal, especially considering how much traction its gained in less than a week

**Comment by Log4Jake** [comment]
After talking with members of the community who are heavily involved with TI, some of them knowing the executives personally, TI probably won't care that much considering there is a pretty high barrier of entry that is this project costs money, time, and some amount of skill to install. I don't support cheating, but I like this project. As a neurodivergent myself and knowing many others in the community, I don't think this is really going to be a problem. This project is way more fun than practical. There are far cheaper and easier ways of cheating. Also, TI would not want to ban their calculator because being allowed on exams is what makes them their money. It is the standard calculator for all exams, books, and curricula. That being said I think this is a really cool project and I think abuse of this is marginally low. People used to use the old trick of using basic to show a fake RAM reset screen. This is probably more likely to happen.

**Comment by BrainwashAlpha** [comment]
@Log4Jake Thank you for your assessment, I do concur, considering the other creative ways TI calculators have been used for cheating or notes before ie. bypassing test mode, custom programs, archiving and unarchiving programs to bypass RAM resets, etc. This is definitely onr of the most convoluted, tim consuming, and resource intensive ways of achieving that.

**Comment by Zekerocks011** [comment]
I mean as a senior (as of writing this) the project makes me want to go out and buy the things necessary to build one or two just because i think it's super cool. Would I cheat in college with it, hell no not worth the risk at all and its college and my future, but could I see myself using this in high school, most definitely. I would not use this on like the SAT though that's way too sketch and way too far. I am very interested to watch how this project goes, and hope that the materials list and everything gets published at some point with PCB schemes and parts

edit: nevermind im blind schemes are literally in a folder on the root LMAO

**Comment by Neoskimmer** [comment]
As a neurodivergent (ADHD, Symptoms of Autism and OCD) highschooler, I feel like a calculator like this would help me pay more attention, and would help me actually LIKE doing the work in classes that I normally hate because of reasons outside my control.

**Comment by alessiodam** [comment]
> After talking with members of the community who are heavily involved with TI, some of them knowing the executives personally, TI probably won't care that much considering there is a pretty high barrier of entry that is this project costs money, time, and some amount of skill to install. I don't support cheating, but I like this project. As a neurodivergent myself and knowing many others in the community, I don't think this is really going to be a problem. This project is way more fun than practical. There are far cheaper and easier ways of cheating. Also, TI would not want to ban their calculator because being allowed on exams is what makes them their money. It is the standard calculator for all exams, books, and curricula. That being said I think this is a really cool project and I think abuse of this is marginally low. People used to use the old trick of using basic to show a fake RAM reset screen. This is probably more likely to happen.

Alright, nice I guess but tell me how 4 people I know already got it 💀
